<?php
function external_help($section = "admin/help#external") {
  $output = '';

  switch ($section) {
    case 'admin/help#external':
      return t('<p>When building a large website, it\'s often useful to distinguish between links
        that refer to this site and those that refer to another site.</p><p>The &quot;External Links&quot;
         module allows the administrator to highlight external links in three ways.</p>
        <ul><li>Make external links open in a new window</li>
        <li>Add a CSS tag to the tag, so it can be highlighted, e.g. in a different colour</li>
        <li>Add an icon to the link</li>');
      break;
    case 'admin/modules#description':
      return t('Highlight external links on your site.');
      break;
    case 'filter#long-tip':
    case 'filter#short-tip':
      return t('external links will be automatically highlighted');
  }
}

function external_help_page() {
  print theme('page', external_help('admin/help#external'));
}

function _external_filter_settings($format) {

  $window = variable_get("external_window_$format", '0');
  $css    = variable_get("external_css_$format", '0');
  $icon   = variable_get("external_icon_$format", '0');
  $file   = variable_get("external_file_$format", '');

  $group  = "<p>These options control the apprearance of external links:</p>";
  $group .= form_checkbox("Open the link in a new window", "external_window_$format", 1, $window, "");
  $group .= form_checkbox("Add a CSS class to the link", "external_css_$format", 1, $css, "");
  $group .= form_checkbox("Add an icon to the link", "external_icon_$format", 1, $icon, "");
  $group .= form_textfield("Icon file", "external_file_$format", $file, 64, 126, "");

  return form_group("External link filter", $group);
}

function external_filter_tips($delta, $format, $long = false) {
  return $long ? external_help('filter#long-tip') : external_help('filter#short-tip');
}

function external_filter($op, $delta = 0, $format = -1, $text = "") {
  switch ($op) {
    case "list":
      return array(0 => t("external filter"));
    case "description":
      return external_help('admin/modules#description');
    case "process":
      return _external_filter_process($format, $text);
    case "settings":
      return _external_filter_settings($format);
    default:
      return $text;
  }
}

function _external_filter_process($format, $text) {

  //cache_clear_all('filter:', true);

  $replace = '*';
  $offset = 0;

  $open  = strpos ($text, '<a',    $offset);
  $href  = strpos ($text, 'href=', $offset + $open);
  $q1    = strpos ($text, '"',     $offset + $href);
  $q2    = strpos ($text, '"',     $offset + $q1 + 1);
  $close = strpos ($text, '>',     $offset + $q2);
  $end   = strpos ($text, '</a>',  $offset + $close);

  /*
  print ("open  = $open<br>");
  print ("href  = $href<br>");
  print ("q1    = $q1<br>");
  print ("q2    = $q2<br>");
  print ("close = $close<br>");
  print ("end   = $end<br>");
  print (drupal_specialchars(substr ($text, $open, $end + 4 - $open)) . "<br>");
  */

  $link = substr ($text, $q1 + 1, $q2 - $q1 - 1);
  if (substr ($link, 0, 7) == "http://") {
    $text = substr ($text, 0, $close) . " class=\"external\"" . substr ($text, $close);
  }

  return $text;
}

?>
