:%s!@pink/black!11!e
:%s!@pink/purple!13!e
:%s!@purple/white!15!e
:%s!@red/white!17!e
:%s!@blue/white!4!e
:%s!@beige!1!e
:%s!@black!2!e
:%s!@blue!3!e
:%s!@brown!5!e
:%s!@features!6!e
:%s!@green!7!e
:%s!@grey!8!e
:%s!@mushroom!9!e
:%s!@orange!10!e
:%s!@pink!12!e
:%s!@purple!14!e
:%s!@red!16!e
:%s!@tiger!18!e
:%s!@turquoise!19!e
:%s!@white!20!e
:%s!@yellow!21!e
