:%s!@Pink/Black!11!e
:%s!@Pink/Purple!13!e
:%s!@Purple/White!15!e
:%s!@Red/White!17!e
:%s!@Blue/White!4!e
:%s!@Beige!1!e
:%s!@Black!2!e
:%s!@Blue!3!e
:%s!@Brown!5!e
:%s!@Features!6!e
:%s!@Green!7!e
:%s!@Grey!8!e
:%s!@Mushroom!9!e
:%s!@Orange!10!e
:%s!@Pink!12!e
:%s!@Purple!14!e
:%s!@Red!16!e
:%s!@Tiger!18!e
:%s!@Turquoise!19!e
:%s!@White!20!e
:%s!@Yellow!21!e
