# merge climb_note table
alter table rating add column notes varchar(255) after climb_note_id;

update rating set notes = "reachy"                                           where climb_note_id = 1;
update rating set notes = "some big moves"                                   where climb_note_id = 2;
update rating set notes = "crazy pullups by the 2nd clip"                    where climb_note_id = 3;
update rating set notes = "very nasty"                                       where climb_note_id = 4;
update rating set notes = "4?"                                               where climb_note_id = 5;
update rating set notes = "fatigue"                                          where climb_note_id = 6;
update rating set notes = "out of my league"                                 where climb_note_id = 7;
update rating set notes = "several falls at the crux.  on top rope"          where climb_note_id = 8;
update rating set notes = "feet on features"                                 where climb_note_id = 9;
update rating set notes = "1 rest"                                           where climb_note_id = 10;
update rating set notes = "6a? 1 rest, pumpy"                                where climb_note_id = 11;
update rating set notes = "top roped, nasty"                                 where climb_note_id = 12;
update rating set notes = "all over the place."                              where climb_note_id = 13;
update rating set notes = "6a+?"                                             where climb_note_id = 14;
update rating set notes = "bit of a reach"                                   where climb_note_id = 15;
update rating set notes = "one very reachy move"                             where climb_note_id = 16;
update rating set notes = "a bit strenuous"                                  where climb_note_id = 17;
update rating set notes = "downclimbable"                                    where climb_note_id = 18;
update rating set notes = "failed at the crux. big rockover"                 where climb_note_id = 19;
update rating set notes = "a few more attempts"                              where climb_note_id = 20;
update rating set notes = "5?"                                               where climb_note_id = 21;
update rating set notes = "nasty"                                            where climb_note_id = 23;
update rating set notes = "did most of it clean, nearly figured out the top" where climb_note_id = 24;
update rating set notes = "did it without the large holes"                   where climb_note_id = 25;
update rating set notes = "strenuous, reachy"                                where climb_note_id = 26;
update rating set notes = "took 3 attempts to get past the dyno start"       where climb_note_id = 27;
update rating set notes = "some big moves above clips"                       where climb_note_id = 29;
update rating set notes = "for a 6b+, top roped"                             where climb_note_id = 30;
update rating set notes = "tiny handholds"                                   where climb_note_id = 31;
update rating set notes = "reachy crux"                                      where climb_note_id = 32;
update rating set notes = "top rope"                                         where climb_note_id = 33;
update rating set notes = "a few rests"                                      where climb_note_id = 34;
update rating set notes = "a few falls"                                      where climb_note_id = 35;
update rating set notes = "technical"                                        where climb_note_id = 36;
update rating set notes = "tricky near the top, downclimbable"               where climb_note_id = 37;
update rating set notes = "big rockover in the middle, downclimbable"        where climb_note_id = 38;
update rating set notes = "big, wide moves"                                  where climb_note_id = 39;
update rating set notes = "weavy"                                            where climb_note_id = 40;
update rating set notes = "treacherous"                                      where climb_note_id = 44;
update rating set notes = "1 fall"                                           where climb_note_id = 45;
update rating set notes = "top roped, 2 falls"                               where climb_note_id = 46;
update rating set notes = "2 falls"                                          where climb_note_id = 47;
update rating set notes = "awkward start"                                    where climb_note_id = 48;
update rating set notes = "6b?"                                              where climb_note_id = 49;
update rating set notes = "tricky, 5+?"                                      where climb_note_id = 50;
update rating set notes = "6a+?"                                             where climb_note_id = 51;
update rating set notes = "awkward start, ok after"                          where climb_note_id = 52;
update rating set notes = "tough, 2 falls"                                   where climb_note_id = 53;
update rating set notes = "yuck horrible holds"                              where climb_note_id = 54;
update rating set notes = "reachy, but ok hand holds"                        where climb_note_id = 56;
update rating set notes = "1 fall - not too bad"                             where climb_note_id = 57;
update rating set notes = "easier this side"                                 where climb_note_id = 59;
update rating set notes = "nearly managed downclimb"                         where climb_note_id = 60;
update rating set notes = "wobbly"                                           where climb_note_id = 61;
update rating set notes = "easy for a 6c"                                    where climb_note_id = 62;
update rating set notes = "2 falls, 6b?"                                     where climb_note_id = 64;
update rating set notes = "very reachy, 2 falls"                             where climb_note_id = 65;
update rating set notes = "1 fall, 6a?"                                      where climb_note_id = 66;
update rating set notes = "leapy"                                            where climb_note_id = 69;
update rating set notes = "many falls"                                       where climb_note_id = 70;
update rating set notes = "no idea how to get started"                       where climb_note_id = 71;
update rating set notes = "now I know"                                       where climb_note_id = 72;
update rating set notes = "reachy, strange route"                            where climb_note_id = 73;

drop trigger t_climb_note_i;
drop trigger t_climb_note_u;
drop trigger t_climb_note_d;
alter table rating drop foreign key rating_ibfk_4;
drop table climb_note;
alter table rating drop column climb_note_id;

delete from data where name = "table_route_note";
delete from data where name = "table_climb_note";

